include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/src/models/generated/**

linter:
  rules:
    cascade_invocations: false
    lines_longer_than_80_chars: false

formatter:
  page_width: 120
